app_name = "compoundinterest"
app_namespace = "comi"
app_repo_url = "https://github.com/BinyaminR/Gitops-compound-interest.git"
app_path = "helm/app-chart"
backend_bucket = "compound-interest-app-binyamin"
argocd_user = "admin"