gcp_credentials = "/home/binyamin/Credentials/bootcamp-project-gke-71790bb0b752.json"
gcp_project_id = "bootcamp-project-gke"
gcp_region = "us-west1"
gke_cluster_name = "binyamin-app"
gke_zones = [ "us-west1-a" ]
gke_network = "default"
gke_subnetwork = "default"
gke_default_nodepool_name = "binyamin-node"
gke_service_account_name = "binyamin-app-sa@bootcamp-project-gke.iam.gserviceaccount.com"
