name: Run App

on:
  push:
    branches:
      - app


jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GCP_CREDENTIALS }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'


    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: ls
      run: 'ls'

    - name: List contents of infrastructure directory
      run: cd app/app && ls -la

      
    - name: Terraform up
      run: 'cd app/app && ./terraform_commands/initiation.sh'

    
      

