name: Run Infrastructure

on:
  push:
    branches:
      - infra


jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GCP_CREDENTIALS }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
       path: infrastructure

    # - name: Write GCP credentials to a file
    #   run: |
    #    cd infrastructure/infrastructure
    #    echo "${{ secrets.GCP_CREDENTIALS_KEY }}" > gcp_creds.json

  
    - name: Set GOOGLE_APPLICATION_CREDENTIALS env variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp_creds.json" >> $GITHUB_ENV

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: List contents of infrastructure directory
      run: cd infrastructure/infrastructure && ls -la

    - name: Terraform up
      run: 'cd infrastructure/infrastructure && ./terraform_commands.sh'

    

      