name: Test

on:
  push:
    branches:
      - infra


jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GCP_CREDENTIALS }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
       path: infrastructure

    - name: Set up GCP credentials
      run: echo "$GOOGLE_APPLICATION_CREDENTIALS_CONTENT" > gcp_creds.json
      
    - name: Set GOOGLE_APPLICATION_CREDENTIALS env variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp_creds.json" >> $GITHUB_ENV

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'


    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: ls
      run: 'ls'

    - name: List contents of infrastructure directory
      run: cd infrastructure/infrastructure && ls -la

    - name: go
      run: 'cd infrastructure/infrastructure'
 
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: 'cd infrastructure/infrastructure && terraform init'

    # Checks that all Terraform configuration files adhere to a canonical format
    # - name: Terraform Format
    #   run: 'cd infrastructure/infrastructure && terraform fmt -check'

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: 'cd infrastructure/infrastructure && terraform plan -input=false'

    - name: Terraform Apply
      run: 'cd infrastructure/infrastructure && terraform apply -auto-approve'

      